### ISSUE TITLE
Allow overriding gradle version to hardcode a specific version

### ISSUE THREAD

**Issue by dakrone** [mopemope/meghanada-server#1]
I work on a project that requires gradle `2.13` due to bugs introduced in later gradle versions, however, when I try to run the server I get:

```
Caused by: org.gradle.api.GradleException: Gradle 2.13 is required to build elasticsearch
	at build_da97v8nh3ew8kq4jfh1zxmavb.run(/home/hinmanm/es/elasticsearch/buildSrc/build.gradle:33)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	... 83 more
```

Because it uses gradle 3.0 from the wrapper.

It would be great if there were a way to tell meghanada to use `gradle` from the `$PATH` rather than the gradle from the wrapper, so the version I need to use explicitly will work.

**Comment by mopemope** [comment]
This is `elasticsearch` side problem.
Server support multi gradle version and detect your project gradle wrapper `./gradlew`.
But `elasticsearch` does not provide gradle wrapper.
(see https://github.com/elastic/elasticsearch/pull/13744 )

**Comment by mopemope** [comment]
Supported override gradle version.

```
$ export MEGHANADA_GRADLE_VERSION=2.13
```
OR
```
$ java -jar path/to//meghanada.jar --gradle-version 2.13 
```

**Comment by dakrone** [comment]
@mopemope thanks for adding that option! It looks like the jar from https://dl.bintray.com/mopemope/meghanada/meghanada.jar is the older version that doesn't support that yet, any idea when it will be updated?

**Comment by mopemope** [comment]
@dakrone already uploaded!

**Comment by dakrone** [comment]
Thanks, I am able to use meghanada now!
