### ISSUE TITLE
Don't use IPv6 on Linux

### ISSUE THREAD

**Issue by rgrinberg** [mopemope/meghanada-server#12]
On Linux, the JVM prefers to listen on IPv6 which your emacs isn't able to connect to. My workaround is to set following environment variable before running meghanada-server:

```
_JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true
```

It would be best if the server listened on IPv4 by default. But ideally, on Linux/OSX it should simply use a Unix domain socket for communication.

**Comment by mopemope** [comment]
Thank you for your report.

**Comment by mopemope** [comment]
@rgrinberg Please check latest version.

**Comment by rgrinberg** [comment]
@mopemope thanks for all the fixes!
