### ISSUE TITLE
jump-declaration doesn't work on enum

### ISSUE THREAD

**Issue by rgrinberg** [mopemope/meghanada-server#14]
Here's an example where go to definition fails:

https://github.com/bdionne/metaproject/blob/master/src/main/java/edu/stanford/protege/metaproject/api/Operation.java#L28

I expect that that when I goto declaration on the `Scope` enum it will take me to it a few lines below. But it doesn't seem to find it.

**Comment by mopemope** [comment]
@rgrinberg Please check latest version.
