### ISSUE TITLE
Java 9 failed to start

### ISSUE THREAD

**Issue by geekerzp** [mopemope/meghanada-server#30]
Meghanada-Server failed to start in Java 9 (oracle64-9-ea)
<img width="1266" alt="2017-06-15 11 17 31" src="https://user-images.githubusercontent.com/2854886/27163767-4dfaeaac-514f-11e7-9e9c-a6508ccb1b7c.png">

**Comment by mopemope** [comment]
@geekerzp  Sorry. JDK 9 is unsupported yet.

**Comment by geekerzp** [comment]
OK. I see
