### ISSUE TITLE
Proposal: create the .meghanada directory outside the project directory

### ISSUE THREAD

**Issue by sdwolf** [mopemope/meghanada-server#31]
The idea is to create the `.meghanada` directory in a path different form te project root so that destructive commands like `git clean -fdx` won't cause problems.

Let's say the project is located in `~/Projects/javaproject`, absolute path `/home/user1/Projects/javaproject`.
What I propose is to have the `.meghanada` directory be located at `~/.cache/meghanada/home/user1/Projects/javaproject`. Another option would be `/tmp/meghanada/home/user1/Projects/javaproject`.

This is how I imagine it:
1) A variable in emacs: `(setq meghanada-directory-in-project t)` which by default is `t` to control this behaviour.
2) A variable in emacs: `(setq meghanada-direcotry-path "~/cache/meghanada")` that controlls the location of the direcotry. Default location TBD.
3) A cli argument `--dir-in-project` with values true or false which controlls the behaviour on the server.
4) A cli argument `--dir-path` with te path of the directory in case 3. is false.
5) A fallback, in case the path is too long revert to creating it in the same directory. This is highly unlinkely to happen but in case it does the server should at least try to work.

I would love for this behaviour to be the default but because of 5) controlling this behaviour from my emacs config seems reasonable.

I am willing to submit PR's with the implementation. But note that I am not an emacs/java expert so it will take some time and it will need some carefull reviews.

**Comment by mopemope** [comment]
@sdwolf Thank you for a good suggestion. Does anyone else have an opinion?

**Comment by sdwolf** [comment]
Looks like the crowd is silent 😃, Is it OK if I start anyway?

**Comment by mopemope** [comment]
@sdwolf Yes. Thank you!

**Comment by sdwolfz** [comment]
Oh wow, I was not involved in any java related work since I opened this issue and it slipped down on my priority list. I'm glad to see you implemented it. While I did try to tackle it myself I got lost in the code and did not manage to get past receiving CLI arguments. Your solution looks way more elegant that what I had in my branch. I can't wait for an opportunity to try it out. Cheers!
