### ISSUE TITLE
Meghanada server uses ~400% CPU for 21 minutes while analyzing project

### ISSUE THREAD

**Issue by dakrone** [mopemope/meghanada-server#4]
When I invoke meghanada-server for my Java project, it uses all of my 4 cores for 21.77 minutes while analyzing the project. Unfortunately that means I can almost never enable it while running on battery on my laptop or else it will be depleted very quickly.

Is there any way to speed this up? Or, could the analysis be cached somehow so it doesn't have to re-analyze when I restart Emacs?

I'm happy to provide the entire log, if that helps, the final message is:

```
[2016-10-03 14:00:38,267][INFO ][CacheEventSubs:  66] on                     - project analyzed elapsed:21.77 min
```

**Comment by mopemope** [comment]
@dakrone Meghanada-server stopped to initial analyze. Please try it 0.2.3.

**Comment by dakrone** [comment]
Thanks this seems better!
