### ISSUE TITLE
Meghanada server should use package relocation

### ISSUE THREAD

**Issue by iocanel** [mopemope/meghanada-server#50]
So, I tried to open a project that is using dependencies that conflict with the meghanda server. An easy way to address this issues is to use package relocation within the server uberjar.

**Comment by mopemope** [comment]
That problem will not occur. 
Could you tell me how to reproduce it?

**Comment by iocanel** [comment]
I am using meghanada to edit a project pretty similar to https://github.com/fabric8io/kubernetes-model. The project uses annotation processors to generate code, and these processors do make use of things like javaparser, which I understand is also used by meghanada. This is causing conflict.

**Comment by iocanel** [comment]
@mopemope: FWIW, relocating `com.github.javaparser` does solve the issue for me.
