### ISSUE TITLE
Smart completion of variable/field based on method return type

### ISSUE THREAD

**Issue by xqliu** [mopemope/meghanada-server#51]
Dear, 

I am thinking about how to implement sort of smart completion, for example,

If we have below code

```
String a = "ABC";
int b = a.
```
Then in this scenario, we might have two kind of completion, described below:

- "Simple completion" which is just the same as current behavior, 
- "Smart completion", which is only fetch back all the possible candidate which with return type int or Integer

I am not sure whether company is possible to support these two kind of completion? 

And also, I saw that the parameter pass to the server from emacs is just a#, which just ignored the part before a. (which is b=, from which we could get return type), so the information is not enough to generate the smart completion candidate.

I am not so familiar with company mode, could you please help on decide whether it's possible to define two kinds of completion mode for company?

But I might be able to do something on the **meghanada--grab-symbol-cons ** part and also pass the variable information to backend server, also do something to filter out only candidates with correct return type.

Thanks :)

**Comment by mopemope** [comment]
No, it must do all of the server. Server analyzed the source, it has type information and expression information and you need to implement it using it.
Contributions are extremely welcome ! 
Thanks.

**Comment by xqliu** [comment]
Already added generic support for the smart completion of assignment.
