### ISSUE TITLE
slf4j conflicts with log4j?

### ISSUE THREAD

**Issue by liujoey** [mopemope/meghanada-server#52]
Hello,

My spring boot project uses gradle for build and slf4j for logging, when I run `meghanada-run-junit-test-case` command, it throws this
`Exception in thread "main" java.lang.ClassCastException: org.apache.logging.slf4j.SLF4JLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext`

My project has not `log4j` dependency, I can run `meghanada-run-task` to run the gradle `test` task without any problem. The test can also be run under IntelliJ fine, so I guess it's meghanada introduced the `log4j` package?

Tried to include `compile group: 'org.slf4j', name: 'log4j-over-slf4j', version: '1.7.25'` package into my project but it doesn't solve the issue.

**Comment by mopemope** [comment]
@liujoey Could you tell me the repository that it reproduces?

**Comment by liujoey** [comment]
I will prepare a repo with some document today.

**Comment by dhirajsurve** [comment]
Removeing  below jar's from class path worked for me 

log4j-to-slf4j-2.0.2.jar
log4j-to-slf4j-2.0.2-sources.jar
log4j-slf4j-impl-2.0.2.jar
log4j-slf4j-impl-2.0.2-sources.jar

**Comment by dquintero2** [comment]
> Removeing below jar's from class path worked for me
> 
> log4j-to-slf4j-2.0.2.jar
> log4j-to-slf4j-2.0.2-sources.jar
> log4j-slf4j-impl-2.0.2.jar
> log4j-slf4j-impl-2.0.2-sources.jar

where did you remove these from?

**Comment by dhirajsurve** [comment]
you can remove them from your project properties from jar list .
