### ISSUE TITLE
[BUG?] Auto completion of import is not working on current dev branch

### ISSUE THREAD

**Issue by xqliu** [mopemope/meghanada-server#59]
[BUG?] Auto completion of import is not working on current dev branch

[Steps to reproduce]

* Create a java file, type `import java.`

[Expect Behavior]

* All the packages under java. should be displayed as candidates

[Current Behavior]

* Only normal word completion candidates from other company backend is displayed.

It seems this is a bug.

**Comment by mopemope** [comment]
@xqliu Thank you for your report.
 
1. Could you check the result of the server is correct ?
2. Could you check the company-mode `no-cache` specification ?
https://github.com/company-mode/company-mode/blob/master/company.el#L378
3. Please add the following settings.

```
(setq company-meghanada-no-cache t)
```

**Comment by xqliu** [comment]
I found the issue might be caused by current definition of `(defconst company-meghanada--trigger "^package \\|^import \\w\\{%d,\\}\\|new \\w\\{%d,\\}\\|@\\w\\{%d,\\}\\|(.*)\\.\\w*\\|[A-Za-z0-9]+\\.\\w*\\|\\.\\w*")`

Will format the request to server side as "match:java.util send-keyword:*java#util", and this caused server try to complete method, not class,  I think the correct request should be "match:import java send-keyword:*import:java.util" to make server try to complete class.

Hope this could help you to fix this issue.

**Comment by xqliu** [comment]
Close as it's not that necessary.
