### ISSUE TITLE
custom formatter rules not being used

### ISSUE THREAD

**Issue by sbaker617** [mopemope/meghanada-server#64]
Version 1.0.3 of the server identifies and reads the formatter rules file meghanadaFormatter.xml but no longer seems to be following the rules specified.  Specifically noticed tabs were now being used instead of spaces when reformatting.

Example project with simplified formatter rules attached.
[unwanted-tabs.tar.gz](https://github.com/mopemope/meghanada-server/files/2056750/unwanted-tabs.tar.gz)

**Comment by mopemope** [comment]
Thank you for your report. I will fix it.

**Comment by sbaker617** [comment]
Thank you for Meghanada :-)
