### ISSUE TITLE
Cannot build meghanda-server

### ISSUE THREAD

**Issue by ilitzroth** [mopemope/meghanada-server#69]
./gradlew --info clean goJF check shadowJar 
Initialized native services in: /home/immanuel/.gradle/native
The client will now receive all logging from the daemon (pid: 5645). The daemon log file: /home/immanuel/.gradle/daemon/4.9/daemon-5645.out.log
Starting 5th build in daemon [uptime: 1 mins 51.022 secs, performance: 100%]
Using 8 worker leases.
Starting Build
Settings evaluated using settings file '/home/immanuel/workspace/code/java-emacs/meghanada-server/settings.gradle'.
Projects loaded. Root project using build file '/home/immanuel/workspace/code/java-emacs/meghanada-server/build.gradle'.
Included projects: [root project 'meghanada-server', project ':server', project ':setup']

> Configure project :
Evaluating root project 'meghanada-server' using build file '/home/immanuel/workspace/code/java-emacs/meghanada-server/build.gradle'.
Configuring signAndPublish task for project :

> Configure project :server
Evaluating project ':server' using build file '/home/immanuel/workspace/code/java-emacs/meghanada-server/server/build.gradle'.

> Configure project :setup
Evaluating project ':setup' using build file '/home/immanuel/workspace/code/java-emacs/meghanada-server/setup/build.gradle'.
All projects evaluated.
Selected primary task 'clean' from project :
Selected primary task 'googleJavaFormat' from project :
Selected primary task 'check' from project :
Selected primary task 'shadowJar' from project :
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/com/android/tools/build/builder-model/3.0.1/builder-model-3.0.1.pom]
Resource missing. [HTTP HEAD: https://repo.maven.apache.org/maven2/com/android/tools/build/builder-model/3.0.1/builder-model-3.0.1.jar]
Resource missing. [HTTP GET: http://repo.gradle.org/gradle/libs-releases-local/com/android/tools/build/builder-model/3.0.1/builder-model-3.0.1.pom]
Resource missing. [HTTP HEAD: http://repo.gradle.org/gradle/libs-releases-local/com/android/tools/build/builder-model/3.0.1/builder-model-3.0.1.jar]
Resource missing. [HTTP GET: https://jcenter.bintray.com/com/android/tools/build/builder-model/3.0.1/builder-model-3.0.1.pom]
Resource missing. [HTTP HEAD: https://jcenter.bintray.com/com/android/tools/build/builder-model/3.0.1/builder-model-3.0.1.jar]

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':server:shadowJar'.
> Could not resolve all dependencies for configuration ':server:runtimeClasspath'.
   > Could not resolve com.android.tools.build:builder-model:3.0.1.
     Required by:
         project :server
      > Could not resolve com.android.tools.build:builder-model:3.0.1.
         > Could not get resource 'https://maven.google.com/com/android/tools/build/builder-model/3.0.1/builder-model-3.0.1.pom'.
            > Could not GET 'https://maven.google.com/com/android/tools/build/builder-model/3.0.1/builder-model-3.0.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Closing Git repo: /home/immanuel/workspace/code/java-emacs/meghanada-server/.git

**Comment by mopemope** [comment]
i can not reproduce it.
