### ISSUE TITLE
Support for JUnit5

### ISSUE THREAD

**Issue by roman** [mopemope/meghanada-server#75]
Hey @mopemope 

Thanks for the work on this project, the more I interact with it, the more impressed I am with its capabilities and usefulness.

I've been playing with meghanada and JUnit5, and noticed that things didn't work as expected. After looking at the meghanada-server's [JUnit](https://github.com/mopemope/meghanada-server/blob/master/server/src/main/java/meghanada/junit/TestRunner.java) support, I noticed it was using the old JUnit4 API and that's why it wasn't working.

I went ahead and tried to add support for [JUnit5 on the meghanada-server codebase](https://github.com/mopemope/meghanada-server/compare/dev...roman:75-junit5-support), and I was able to make it work. However, my changes made the JUnit4 API stop working, which I'm guessing is less than ideal.

I want to get feedback from you and ask:

* Would you like me to do a Pull Request with my changes? 
* Do you know if there is a clever way to support JUnit4 tests on a client project while meghanada-server is working with JUnit5?

Thanks for your time.

P.S: side note, I got the ["No processor claimed any of these annotations"](https://github.com/mopemope/meghanada-emacs/issues/97) error and had to modify the `meghanada-javac-xlint` to make it work.

**Comment by mopemope** [comment]
@roman I am welcoming your contribution. How about using `org.junit.vintage` ?

**Comment by roman** [comment]
I'll give it a try and add `org.junit.vintage` as an import to the meghanada's customer runner and see if JUnit4 tests get discovered. If this doesn't work, I'll still create the merge request; in this situation maybe adding a comment somewhere saying that JUnit4 support is being dropped might be a good idea.

**Comment by mopemope** [comment]
@roman I also tried implementing it. Could you confirm with the `dev` branch?

**Comment by roman** [comment]
Sadly, when using JUnit4 dependencies in gradle and JUnit4 imports (e.g. `import org.junit.*`), the new JUnit5 runner is not able to recognize the methods (or the class) as tests.

**Comment by roman** [comment]
^^^ @mopemope

**Comment by roman** [comment]
@mopemope the functionality works for the newer JUnit5 version as of [this commit](https://github.com/mopemope/meghanada-server/commit/566d56e030f522cc2a913c9965056aed149ab324), as such, I will close this ticket now. 

On a side note, not a big deal, but for future collaborations, I would highly appreciate if my commits get in the repository history as well (if you don't mind of course).

Cheers, and thank you for creating and maintaining this project.

**Comment by mopemope** [comment]
@roman I really appreciate you. Thank you very much!
