### ISSUE TITLE
Add dependencies list generation in documentation

### ISSUE THREAD

**Issue by rakotomandimby** [mopemope/meghanada-server#83]
In order to fill the dependencies in `.meghanada.conf`, I fire this:
```
mvn dependency:build-classpath \
    -Dmdep.pathSeparator="," \
    -Dmdep.prefix='' \
    -Dmdep.fileSeparator="@" \
    -Dmdep.outputFile=/tmp/classpath
```
```
awk -F, '{} 
  { for(i = 1; i <= NF; i++)
    {p=$i; gsub("@","",p); print "find ~/.m2 -type f -name ",p; }
  }'  < /tmp/classpath | bash | awk '{print "\""$0"\","}'
```
It should be a good idea to put this into the sample file or document it in the README.

**Comment by mopemope** [comment]
The maven project is already supported. I think that is not necessary.

**Comment by rakotomandimby** [comment]
@mopemope , when I add a dependency in pom.xml and then restart meghanada-server, autocomplete on the added artifact is still missing.
