### ISSUE TITLE
downloadJar needs to handle the case where it fails

### ISSUE THREAD

**Issue by rakotomandimby** [mopemope/meghanada-server#85]
https://github.com/mopemope/meghanada-server/blob/b22445e9e05d3c51227dd64d37fe37fb5a55a8e1/setup/src/main/java/meghanada/SetupMain.java#L121

When running in a very restrictive environment (corporate Proxy), this download might fail.
The faillure needs to be handled.

**Comment by mopemope** [comment]
@rakotomandimby In the latest version, you can set proxy an etc.

```
 (setq meghanada-jvm-option "-Dhttp.proxyHost=test.proxy.com -Dhttp.proxyPort=8080")
```
