### ISSUE TITLE
exclude-file broken in .meghanada.conf

### ISSUE THREAD

**Issue by JoshLitt** [mopemope/meghanada-server#86]
Line 801 here has a typo, when trying to look for EXCLUDE_FILE, we instead look for INCLUDE_FILE.

https://github.com/mopemope/meghanada-server/blob/046625248556d61f2b730b32f144a789528586c8/server/src/main/java/meghanada/project/Project.java#L800-L802

**Comment by mopemope** [comment]
@JoshLitt Thank you for your report!. I will fix it soon.
