### ISSUE TITLE
dev branch: downloads Gradle

### ISSUE THREAD

**Issue by rakotomandimby** [mopemope/meghanada-server#87]
In order to build meghanada-server, one needs to have Gradle in the PATH.
But when invoking ``gradlew clean goJF check shadowJar`` in order to build, its first action is to download Gradle.

**Comment by mopemope** [comment]
This project is being tested using the latest gradle.
Please call the following document.
https://docs.gradle.org/current/userguide/gradle_wrapper.html

And if you want to use gradle in your environment, use the `gradle` command.
