### ISSUE TITLE
Java 8 test failures

### ISSUE THREAD

**Issue by ccarlow** [mopemope/meghanada-server#93]
Initially I was building with Java 12 but saw from #84 that Java 8 is used for testing.  Java 8 fails also but with different test cases.  I thought master may be unstable so I tried that latest release 1.2.0 but it fails also.

Failed test cases prevent the server jar from being generated.

Running gradlew without the check argument (./gradlew clean goJF shadowJar)   allows the project to build successfully and generate the jar.

**Comment by mopemope** [comment]
Because you need Java source for testing.
